import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Upload, Camera, RefreshCw, CheckCircle2, AlertCircle, AlertTriangle,
  Save, Sparkles, ShieldCheck, Zap, Scan, Activity, FileText, ArrowRight, X, TrendingUp, MessageCircle
} from 'lucide-react';
import { mockApi } from '../services/api';
import { db, auth } from '../firebase';
import { collection, addDoc } from 'firebase/firestore';
import { useNavigate } from 'react-router-dom';
import AppFooter from '../components/AppFooter';

import { compressImage } from '../utils/imageUtils';
import { useLanguage } from '../context/LanguageContext';

const DetectionPage = () => {
  const [image, setImage] = useState(null);
  const [preview, setPreview] = useState(null);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [nickname, setNickname] = useState('');
  const [savedSuccess, setSavedSuccess] = useState(false);
  const [stageIdx, setStageIdx] = useState(0);
  const [scanTime, setScanTime] = useState(0);
  const [timerActive, setTimerActive] = useState(false);
  const [userProfile, setUserProfile] = useState(null);
  const navigate = useNavigate();
  const { t, language } = useLanguage();

  const stages = [t('inv.stage1'), t('det.analyzingLeaf'), t('det.comparingDatabase'), t('det.generatingReport')];

  useEffect(() => {
    if (!loading) { setStageIdx(0); return; }
    const timer = setInterval(() => setStageIdx(p => Math.min(p + 1, stages.length - 1)), 250);
    return () => clearInterval(timer);
  }, [loading]);

  useEffect(() => {
    let interval;
    if (timerActive) {
      interval = setInterval(() => {
        setScanTime(prev => +(prev + 0.1).toFixed(1));
      }, 100);
    } else {
      clearInterval(interval);
    }
    return () => clearInterval(interval);
  }, [timerActive]);

  useEffect(() => {
    if (auth.currentUser) {
      const fetchProfile = async () => {
        try {
          const docRef = doc(db, 'users', auth.currentUser.uid);
          const docSnap = await getDoc(docRef);
          if (docSnap.exists()) setUserProfile(docSnap.data());
        } catch (e) {
          console.error("Error fetching profile:", e);
        }
      };
      fetchProfile();
    }
  }, []);

  const currentContent = result ? (result[language] || result.en || {}) : {};

  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setImage(file);
      setPreview(URL.createObjectURL(file));
      setResult(null);
      setError(null);
      setSavedSuccess(false);
    }
  };

  const analyzeImage = async () => {
    if (!image) return;
    setLoading(true);
    setResult(null);
    setError(null);
    setScanTime(0);
    setTimerActive(true);
    
    const localPreview = preview || URL.createObjectURL(image);

    try {
      const b64 = await compressImage(image, { maxWidth: 640, maxHeight: 640, quality: 0.6 });
      
      const detectionPromise = mockApi.predictDisease(b64, language);
      const uploadPromise = mockApi.uploadToImgBB(b64).catch(e => null);

      const data = await Promise.race([
        detectionPromise,
        new Promise((_, reject) => setTimeout(() => reject(new Error("DETECTION_TIMEOUT")), 60000))
      ]);

      setTimerActive(false); // Stop timer immediately on data

      const imgUrl = await Promise.race([
        uploadPromise,
        new Promise(resolve => setTimeout(() => resolve(null), 2500))
      ]) || localPreview;

      data.imgUrl = imgUrl;
      setResult(data);
    } catch (err) {
      setTimerActive(false);
      console.error("Scanning error:", err);
      setError(err.message === "DETECTION_TIMEOUT" ? "Scan took too long. Please try again." : t('det.errGeneric'));
    } finally {
      setLoading(false);
    }
  };

  const shareToWhatsApp = () => {
    if (!result) return;
    const crop = currentContent.cropName || result.cropName;
    const diag = currentContent.diagnosis || result.diagnosis;
    const score = result.healthScore;
    const sev = result.severity;
    
    let text = `*KrishiAI Crop Health Report*\n\n`;
    text += `🌱 *Crop:* ${crop}\n`;
    text += `🔍 *Diagnosis:* ${diag}\n`;
    text += `🏥 *Health Score:* ${score}%\n`;
    text += `⚠️ *Severity:* ${sev.toUpperCase()}\n\n`;
    
    if (currentContent.summary) {
      text += `📝 *Summary:* ${currentContent.summary}\n\n`;
    }
    
    if (currentContent.solution && currentContent.solution.length > 0) {
      text += `💡 *Expert Solutions:*\n`;
      currentContent.solution.forEach(s => {
        text += `• ${s.title}: ${s.detail}\n`;
      });
    }
    
    text += `\n🔬 _Generated by KrishiAI Diagnostic Intelligence_`;
    
    const encodedText = encodeURIComponent(text);
    const phoneNum = userProfile?.phone ? userProfile.phone.replace(/[^0-9]/g, '') : '';
    window.open(`https://wa.me/${phoneNum}?text=${encodedText}`, '_blank');
  };

  const saveToDashboard = async () => {
    if (!auth || !db) {
      setError(t('det.errOffline'));
      return;
    }
    if (!result || !auth.currentUser) {
      setError(t('det.errSignIn'));
      return;
    }
    setSaving(true);
    try {
      const scanTimestamp = new Date().toISOString();
      await addDoc(collection(db, "crops"), {
        name: nickname || result.cropName,
        problem: result.diagnosis,
        type: "Scan",
        status: result.status,
        diagnosis: result.diagnosis,
        summary: result.en?.summary || '',
        solve: result.en?.solution?.map(s => s.detail).join('. ') || '',
        prevent: result.en?.prevention?.map(p => p.detail).join('. ') || '',
        healthScore: result.healthScore || 0,
        severity: result.severity,
        confidence: result.confidence,
        imageUrl: result.imgUrl,
        lastScanned: scanTimestamp,
        lastScanFull: {
          en: result.en || result.lastScanFull?.en || {},
          hi: result.hi || result.en || {},
          te: result.te || result.en || {},
          ta: result.ta || result.en || {},
          bn: result.bn || result.en || {},
          mr: result.mr || result.en || {},
          cropName: result.cropName,
          diagnosis: result.diagnosis,
          severity: result.severity,
          confidence: result.confidence,
          healthScore: result.healthScore,
          status: result.status,
          imgUrl: result.imgUrl,
        },
        scanHistory: [
          { score: result.healthScore || 0, date: scanTimestamp, status: result.status, diagnosis: result.diagnosis }
        ],
        userId: auth.currentUser.uid,
        createdAt: scanTimestamp,
      });
      setSavedSuccess(true);
      setTimeout(() => navigate('/dashboard'), 1500);
    } catch (err) {
      setError(t('det.errSave'));
    } finally {
      setSaving(false);
    }
  };

  const severityColor = (s) => {
    const sev = String(s).toLowerCase();
    if (sev === 'critical') return { bg: '#2d1414', border: '#7f1d1d', text: '#fca5a5', dot: '#ef4444' };
    if (sev === 'high') return { bg: '#2d1f0e', border: '#78350f', text: '#fcd34d', dot: '#f59e0b' };
    return { bg: '#0e2118', border: '#14532d', text: '#6ee7b7', dot: '#10b981' };
  };

  return (
    <div className="dp-root">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=JetBrains+Mono:wght@400;500;700&family=Outfit:wght@400;500;600;700;800&display=swap');

        .dp-root {
          min-height: 100vh;
          background: #f4f7f2;
          color: #1a2e14;
          font-family: 'Outfit', sans-serif;
          padding-top: 88px;
          padding-bottom: 80px;
          position: relative;
          overflow-x: hidden;
        }

        /* ── grid texture bg ── */
        .dp-root::before {
          content: '';
          position: fixed;
          inset: 0;
          background-image:
            linear-gradient(rgba(46,160,80,.06) 1px, transparent 1px),
            linear-gradient(90deg, rgba(46,160,80,.06) 1px, transparent 1px);
          background-size: 40px 40px;
          pointer-events: none;
          z-index: 0;
        }

        /* ── glows ── */
        .dp-glow-tl {
          position: fixed; top: -120px; left: -120px;
          width: 500px; height: 500px; border-radius: 50%;
          background: radial-gradient(circle, rgba(34,197,94,.13) 0%, transparent 70%);
          pointer-events: none; z-index: 0;
        }
        .dp-glow-br {
          position: fixed; bottom: -100px; right: -100px;
          width: 420px; height: 420px; border-radius: 50%;
          background: radial-gradient(circle, rgba(234,179,8,.10) 0%, transparent 70%);
          pointer-events: none; z-index: 0;
        }

        .dp-wrap {
          max-width: 1140px;
          margin: 0 auto;
          padding: 0 24px;
          position: relative;
          z-index: 1;
        }

        /* ── HEADER ── */
        .dp-header {
          display: flex;
          align-items: flex-start;
          justify-content: space-between;
          margin-bottom: 48px;
          gap: 16px;
        }
        .dp-header-eyebrow {
          display: flex;
          align-items: center;
          gap: 8px;
          font-family: 'JetBrains Mono', monospace;
          font-size: 10px;
          font-weight: 700;
          letter-spacing: .18em;
          color: #4ade80;
          text-transform: uppercase;
          margin-bottom: 10px;
        }
        .dp-header-eyebrow-dot {
          width: 6px; height: 6px; border-radius: 50%;
          background: #4ade80;
          animation: dp-pulse 2s ease-in-out infinite;
        }
        @keyframes dp-pulse { 0%,100%{opacity:1} 50%{opacity:.3} }
        .dp-title {
          font-family: 'DM Serif Display', serif;
          font-size: clamp(36px, 6vw, 64px);
          font-style: italic;
          line-height: 1;
          color: #14281a;
          margin: 0;
        }
        .dp-title-accent {
          font-style: normal;
          background: linear-gradient(120deg, #4ade80 0%, #eab308 100%);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
        }
        .dp-close-btn {
          width: 44px; height: 44px; border-radius: 12px;
          background: #ffffff; border: 1px solid #d4e4cc;
          color: #5a7850; cursor: pointer;
          display: flex; align-items: center; justify-content: center;
          transition: all .18s; flex-shrink: 0;
        }
        .dp-close-btn:hover { background: #1e2419; color: #1a2e14; border-color: #3d4f35; }

        /* ── MAIN GRID ── */
        .dp-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 24px;
          align-items: start;
        }
        @media (max-width: 900px) {
          .dp-grid { grid-template-columns: 1fr; }
        }

        /* ── UPLOAD PANEL ── */
        .dp-upload-panel {
          background: #ffffff;
          border: 1px solid #dcebd6;
          border-radius: 24px;
          overflow: hidden;
        }
        .dp-panel-label {
          padding: 16px 20px 14px;
          border-bottom: 1px solid #e8f0e4;
          display: flex;
          align-items: center;
          gap: 10px;
          font-family: 'JetBrains Mono', monospace;
          font-size: 10px;
          font-weight: 700;
          letter-spacing: .16em;
          color: #4a7a40;
          text-transform: uppercase;
        }
        .dp-panel-label-num {
          width: 20px; height: 20px; border-radius: 6px;
          background: #e8f5e2; border: 1px solid #b8ddb0;
          display: flex; align-items: center; justify-content: center;
          font-size: 9px; color: #16a34a; font-weight: 700;
        }

        /* image frame */
        .dp-img-frame {
          position: relative;
          aspect-ratio: 1;
          margin: 16px;
          border-radius: 16px;
          overflow: hidden;
          background: #f8faf6;
          border: 1px dashed #c8ddc0;
          display: flex;
          align-items: center;
          justify-content: center;
          transition: border-color .2s;
        }
        .dp-img-frame.has-image {
          border-style: solid;
          border-color: #6ab860;
        }
        .dp-img-frame img {
          width: 100%; height: 100%; object-fit: cover;
          border-radius: 14px;
        }
        .dp-img-overlay {
          position: absolute; inset: 0;
          background: rgba(0,0,0,.55);
          display: flex; align-items: center; justify-content: center;
          opacity: 0; transition: opacity .2s;
          border-radius: 14px;
        }
        .dp-img-frame.has-image:hover .dp-img-overlay { opacity: 1; }
        .dp-img-refresh {
          width: 44px; height: 44px; border-radius: 50%;
          background: rgba(255,255,255,.15);
          border: none; color: #fff; cursor: pointer;
          display: flex; align-items: center; justify-content: center;
          transition: background .15s;
        }
        .dp-img-refresh:hover { background: rgba(255,255,255,.28); }

        /* upload label */
        .dp-upload-label {
          display: flex; flex-direction: column;
          align-items: center; gap: 16px;
          cursor: pointer; padding: 32px;
          width: 100%;
        }
        .dp-upload-icon {
          width: 64px; height: 64px; border-radius: 18px;
          background: #f0f8ec; border: 1px solid #d0e8c8;
          display: flex; align-items: center; justify-content: center;
          color: #6a9060; transition: all .18s;
        }
        .dp-upload-label:hover .dp-upload-icon {
          background: #e2f5dc; border-color: #4ade80; color: #16a34a;
        }
        .dp-upload-text-main {
          font-size: 12px; font-weight: 700;
          color: #2a4a22; letter-spacing: .06em;
          text-transform: uppercase;
        }
        .dp-upload-text-sub {
          font-family: 'JetBrains Mono', monospace;
          font-size: 10px; color: #6a9060;
          letter-spacing: .1em; text-transform: uppercase;
          margin-top: 4px;
        }

        /* scan line animation */
        .dp-scanline {
          position: absolute; left: 0; right: 0;
          height: 2px;
          background: linear-gradient(90deg, transparent, #4ade80, transparent);
          box-shadow: 0 0 12px #4ade8066;
          z-index: 10;
        }

        /* scan button */
        .dp-scan-btn {
          margin: 0 16px 16px;
          width: calc(100% - 32px);
          padding: 16px;
          border-radius: 14px;
          border: none;
          font-family: 'JetBrains Mono', monospace;
          font-size: 11px; font-weight: 700;
          letter-spacing: .14em; text-transform: uppercase;
          cursor: pointer;
          display: flex; align-items: center; justify-content: center; gap: 10px;
          transition: all .18s;
        }
        .dp-scan-btn.ready {
          background: linear-gradient(135deg, #1a3d18, #2d6b28);
          color: #a7f3d0;
          box-shadow: 0 4px 24px rgba(74,222,128,.18);
        }
        .dp-scan-btn.ready:hover {
          background: linear-gradient(135deg, #1f4d1c, #347a2e);
          box-shadow: 0 6px 32px rgba(74,222,128,.26);
        }
        .dp-scan-btn.disabled {
          background: #f0f2ee;
          color: #b8c8b0;
          cursor: not-allowed;
        }

        /* ── RESULT PANEL OVERHAUL ── */
        .dp-result-panel {
          background: #ffffff;
          border: 1px solid #dcebd6;
          border-radius: 32px;
          overflow: hidden;
          box-shadow: 0 10px 40px rgba(26,46,20,0.04);
        }

        .dp-result-hero {
          padding: 32px 24px;
          background: linear-gradient(180deg, #f8faf6 0%, #ffffff 100%);
          border-bottom: 1px solid #e8f0e4;
        }

        .dp-status-pill {
          display: inline-flex;
          align-items: center;
          gap: 6px;
          padding: 6px 12px;
          background: #f0faf4;
          border: 1px solid #d1fae5;
          border-radius: 100px;
          font-family: 'JetBrains Mono', monospace;
          font-size: 9px;
          font-weight: 800;
          color: #059669;
          text-transform: uppercase;
          letter-spacing: 0.1em;
          margin-bottom: 16px;
        }

        .dp-crop-title {
          font-family: 'DM Serif Display', serif;
          font-size: 36px;
          color: #14281a;
          line-height: 1.1;
          margin: 0 0 4px 0;
        }

        .dp-diag-value {
          margin-bottom: 20px;
        }

        .dp-highlight-pill {
          background: #fef08a;
          color: #1a2e14;
          padding: 4px 12px;
          border-radius: 12px;
          box-shadow: 0 4px 15px rgba(234, 179, 8, 0.15);
          display: inline-block;
          position: relative;
          z-index: 1;
        }

        .dp-marker-title {
          background: linear-gradient(to top, #dcfce7 40%, transparent 40%);
          padding: 0 4px;
        }

        .dp-meta-row {
          display: flex;
          flex-wrap: wrap;
          gap: 8px;
          align-items: center;
        }

        .dp-conf-badge {
          font-family: 'JetBrains Mono', monospace;
          font-size: 10px;
          font-weight: 700;
          color: #4a7a40;
          background: #f8faf6;
          border: 1px solid #e2ebd9;
          padding: 4px 10px;
          border-radius: 8px;
          text-transform: uppercase;
        }

        .dp-sev-tag {
          display: flex;
          align-items: center;
          gap: 6px;
          padding: 4px 12px;
          border-radius: 8px;
          font-family: 'JetBrains Mono', monospace;
          font-size: 10px;
          font-weight: 800;
          text-transform: uppercase;
          border: 1px solid;
        }

        .dp-sev-dot {
          width: 5px; height: 5px; border-radius: 50%;
        }

        .dp-health-module {
          padding: 24px;
          border-bottom: 1px solid #e8f0e4;
        }

        .dp-meter-track {
          height: 12px;
          background: #f0f4ec;
          border-radius: 100px;
          overflow: hidden;
          position: relative;
        }

        .dp-meter-fill {
          height: 100%;
          background: linear-gradient(90deg, #16a34a, #4ade80, #fbbf24);
          background-size: 200% 100%;
          border-radius: 100px;
        }

        .dp-insight-card {
          margin: 20px 24px;
          padding: 20px;
          background: #fdfdfd;
          border: 1px solid #f0f4f0;
          border-radius: 20px;
          position: relative;
        }

        .dp-protocol-section {
          padding: 10px 24px 32px;
        }

        .dp-protocol-step {
          display: flex;
          gap: 16px;
          padding: 16px;
          background: #ffffff;
          border: 1px solid #f0f4f0;
          border-radius: 16px;
          transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
        }

        .dp-protocol-step:hover {
          transform: translateY(-2px);
          border-color: #d1fae5;
          box-shadow: 0 4px 12px rgba(16, 185, 129, 0.05);
        }

        .dp-step-marker {
          width: 32px;
          height: 32px;
          background: #1a2e14;
          color: #fff;
          border-radius: 10px;
          display: flex;
          align-items: center;
          justify-content: center;
          font-family: 'JetBrains Mono', monospace;
          font-size: 12px;
          font-weight: 800;
          flex-shrink: 0;
        }

        .dp-input-chip {
           padding: 16px;
           border-radius: 16px;
           border: 1px solid;
           margin: 0 24px 12px;
        }
        .dp-input-chip.nutrient { background: #f0fdf4; border-color: #dcfce7; }
        .dp-input-chip.protector { background: #fff1f2; border-color: #ffe4e6; }

        @media (max-width: 640px) {
           .dp-crop-title { font-size: 28px; }
           .dp-diag-value { font-size: 16px; }
           .dp-result-panel { border-radius: 24px; }
           .dp-protocol-step { padding: 12px; }
        }

        /* success */
        .dp-success {
          margin: 20px 24px 24px;
          padding: 24px;
          background: linear-gradient(135deg, #f0faf4, #e4f7ec);
          border: 1px solid #b0d8bc;
          border-radius: 16px;
          text-align: center;
          display: flex; flex-direction: column;
          align-items: center; gap: 10px;
        }
        .dp-success-icon {
          width: 48px; height: 48px; border-radius: 50%;
          background: #d1fae5; border: 1px solid #6ee7b7;
          display: flex; align-items: center; justify-content: center;
          color: #4ade80;
        }
        .dp-success-title {
          font-family: 'DM Serif Display', serif;
          font-size: 20px; font-style: italic; color: #065f46;
        }
        .dp-success-sub {
          font-family: 'JetBrains Mono', monospace;
          font-size: 9px; color: #4a7a40;
          letter-spacing: .12em; text-transform: uppercase;
        }

        /* error */
        .dp-error {
          padding: 48px 32px;
          text-align: center;
          display: flex; flex-direction: column;
          align-items: center; gap: 16px;
        }
        .dp-error-icon {
          width: 56px; height: 56px; border-radius: 16px;
          background: #fff4f4; border: 1px solid #f0b8b8;
          display: flex; align-items: center; justify-content: center;
          color: #dc2626;
        }
        .dp-error-text {
          font-family: 'JetBrains Mono', monospace;
          font-size: 10px; color: #dc2626;
          letter-spacing: .1em; text-transform: uppercase;
          line-height: 1.6;
        }

        /* idle state */
        .dp-idle {
          padding: 64px 32px;
          text-align: center;
          display: flex; flex-direction: column;
          align-items: center; gap: 16px;
        }
        .dp-idle-icon {
          width: 64px; height: 64px; border-radius: 20px;
          background: #f8faf6; border: 1px dashed #c8d8c0;
          display: flex; align-items: center; justify-content: center;
          color: #c0d0b8;
        }
        .dp-idle-text {
          font-family: 'JetBrains Mono', monospace;
          font-size: 10px; color: #a8c0a0;
          letter-spacing: .14em; text-transform: uppercase;
        }
      `}</style>

      <div className="dp-glow-tl" />
      <div className="dp-glow-br" />

      <div className="dp-wrap">
        {/* ── HEADER ── */}
        <motion.header
          className="dp-header"
          initial={{ opacity: 0, y: -16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
        >
          <div>
            <div className="dp-header-eyebrow">
              <span className="dp-header-eyebrow-dot" />
              {t('det.fieldHealthScanner')}
            </div>
            <h1 className="dp-title">
              {t('det.title')} <span className="dp-title-accent"></span>
            </h1>
          </div>
          <button className="dp-close-btn" onClick={() => navigate('/dashboard')}>
            <X size={20} />
          </button>
        </motion.header>

        {/* ── MAIN GRID ── */}
        <div className="dp-grid">

          {/* ── LEFT: Upload Panel ── */}
          <motion.div
            className="dp-upload-panel"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.4, delay: 0.1 }}
          >
            <div className="dp-panel-label">
              <span className="dp-panel-label-num">01</span>
              {t('det.selectBioImagery')}
            </div>

            <div className={`dp-img-frame ${preview ? 'has-image' : ''}`}>
              {preview ? (
                <>
                  <motion.img
                    initial={{ scale: 1.08 }}
                    animate={{ scale: 1 }}
                    transition={{ duration: 0.5 }}
                    src={preview}
                    alt="preview"
                  />
                  <div className="dp-img-overlay">
                    <button
                      className="dp-img-refresh"
                      onClick={() => { setImage(null); setPreview(null); setResult(null); }}
                    >
                      <RefreshCw size={20} />
                    </button>
                  </div>
                </>
              ) : (
                <label className="dp-upload-label">
                  <div className="dp-upload-icon">
                    <Upload size={28} />
                  </div>
                  <div style={{ textAlign: 'center' }}>
                    <p className="dp-upload-text-main">{t('det.upload')}</p>
                    <p className="dp-upload-text-sub">{t('det.subtitle')}</p>
                  </div>
                  <input type="file" style={{ display: 'none' }} accept="image/*" onChange={handleImageChange} />
                </label>
              )}

              <AnimatePresence>
                {loading && (
                  <motion.div
                    className="dp-scanline"
                    initial={{ top: '0%' }}
                    animate={{ top: '100%' }}
                    transition={{ duration: 1.5, repeat: Infinity, ease: 'linear' }}
                  />
                )}
              </AnimatePresence>
            </div>

            <motion.button
              whileTap={{ scale: 0.97 }}
              onClick={analyzeImage}
              disabled={!image || loading}
              className={`dp-scan-btn ${!image || loading ? 'disabled' : 'ready'}`}
            >
              {loading
                ? <><RefreshCw size={16} style={{ animation: 'spin 1.5s linear infinite' }} /> {stages[stageIdx]} ({scanTime}s)</>
                : result
                  ? <><RefreshCw size={16} /> Scan Again (Last: {scanTime}s)</>
                  : <><Scan size={16} /> {t('det.analyze')} <ArrowRight size={14} /></>
              }
            </motion.button>
          </motion.div>

          {/* ── RIGHT: Result Panel ── */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.4, delay: 0.15 }}
          >
            <AnimatePresence mode="wait">
              {result ? (
                <motion.div
                  key="result"
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="dp-result-panel"
                >
                  {/* --- Diagnosis Quick Header --- */}
                  <div className="dp-result-hero">
                    <div className="dp-status-pill">
                       <Zap size={10} className="fill-current" /> {t('det.scannedSuccess')} — {scanTime}s
                    </div>
                    <h2 className="dp-crop-title">{currentContent.cropName || result.cropName}</h2>
                    <div className="dp-diag-wrapper">
                      <h3 className="dp-diag-value">
                        <span className="dp-highlight-pill">
                          {currentContent.diagnosis || result.diagnosis}
                        </span>
                      </h3>
                    </div>
                    
                    <div className="dp-meta-row">
                      <div className="dp-conf-badge">
                        {result.confidence}% {t('det.precision')}
                      </div>
                      <div
                        className="dp-sev-tag"
                        style={{
                          background: severityColor(result.severity).bg,
                          color: severityColor(result.severity).text,
                          borderColor: severityColor(result.severity).border
                        }}
                      >
                        <span className="dp-sev-dot" style={{ background: severityColor(result.severity).dot }} />
                        {t(`common.${String(result.severity).toLowerCase()}`)}
                      </div>
                    </div>
                  </div>

                  {/* --- Precision Health Meter --- */}
                  <div className="dp-health-module">
                    <div className="flex justify-between items-end mb-3">
                      <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{t('det.trueHealth')}</span>
                      <span className="text-2xl font-black text-slate-900">{result.healthScore}%</span>
                    </div>
                    <div className="dp-meter-track">
                      <motion.div
                        className="dp-meter-fill"
                        initial={{ width: 0 }}
                        animate={{ width: `${result.healthScore}%` }}
                        transition={{ duration: 1.2, ease: "circOut" }}
                      />
                    </div>
                    <p className="text-[10px] text-slate-400 font-bold mt-2 italic">Based on deep morphological AI analysis</p>
                  </div>

                  {/* --- Expert Summary --- */}
                  {currentContent.summary && (
                    <div className="dp-insight-card">
                      <div className="flex items-center gap-2 mb-3">
                        <div className="w-8 h-8 rounded-full bg-krishi-50 flex items-center justify-center text-krishi-600">
                          <Activity size={14} />
                        </div>
                        <span className="text-[11px] font-black text-slate-900 uppercase tracking-wider">{t('det.deepAnalysis')}</span>
                      </div>
                      <p className="text-sm text-slate-600 leading-relaxed font-medium">
                        "{currentContent.summary}"
                      </p>
                    </div>
                  )}

                  {/* --- Actionable Protocol --- */}
                  <div className="dp-protocol-section">
                    <div className="flex items-center justify-between mb-6">
                      <h4 className="text-sm font-black text-slate-900 uppercase tracking-widest">{t('det.solution')}</h4>
                      <div className="px-3 py-1 bg-slate-900 text-[9px] font-black text-white rounded-full uppercase tracking-tighter">Verified Protocol</div>
                    </div>

                    <div className="space-y-4">
                      {currentContent.solution?.map((s, idx) => (
                        <div key={idx} className="dp-protocol-step">
                          <div className="dp-step-marker">{idx + 1}</div>
                          <div className="flex-1">
                            <p className="text-sm font-black text-slate-900 mb-1">
                              <span className="dp-marker-title">{s.title}</span>
                            </p>
                            <p className="text-xs text-slate-500 font-medium leading-normal mb-2">{s.detail}</p>
                            <div className="inline-flex items-center gap-1.5 px-2 py-0.5 bg-amber-50 text-amber-600 rounded text-[9px] font-black uppercase">
                               <RefreshCw size={9} /> {s.urgency}
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* --- Material Inputs --- */}
                  {(currentContent.fertilizer || currentContent.pesticide) && (
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-8">
                       {currentContent.fertilizer && (
                         <div className="dp-input-chip nutrient">
                            <div className="flex items-center gap-2 mb-2">
                               <TrendingUp size={12} className="text-emerald-600" />
                               <span className="text-[9px] font-black uppercase text-emerald-700 tracking-tighter">Nutrient Boost</span>
                            </div>
                            <p className="text-[13px] font-bold text-slate-800">{currentContent.fertilizer}</p>
                         </div>
                       )}
                       {currentContent.pesticide && (
                         <div className="dp-input-chip protector">
                            <div className="flex items-center gap-2 mb-2">
                               <ShieldCheck size={12} className="text-rose-600" />
                               <span className="text-[9px] font-black uppercase text-rose-700 tracking-tighter">Plant Medicine</span>
                            </div>
                            <p className="text-[13px] font-bold text-slate-800">{currentContent.pesticide}</p>
                         </div>
                       )}
                    </div>
                  )}

                  {/* --- Footer Actions --- */}
                  {!savedSuccess ? (
                    <div className="mt-12 pt-8 border-t border-slate-100">
                      <div className="dp-label-input-group mb-6">
                        <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-2 px-2">Reference Nickname</label>
                        <div className="relative">
                          <FileText size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
                          <input
                            type="text"
                            placeholder={t('det.researchLabel')}
                            className="w-full pl-12 pr-6 py-4 bg-slate-50 border-2 border-transparent focus:border-krishi-300 rounded-2xl outline-none font-bold text-slate-900 transition-all placeholder:text-slate-300"
                            value={nickname}
                            onChange={e => setNickname(e.target.value)}
                          />
                        </div>
                      </div>

                      <div className="flex flex-col gap-3">
                        <button
                          className="w-full py-5 bg-[#25d366] text-white rounded-[1.2rem] font-black text-xs uppercase tracking-widest shadow-xl shadow-green-500/10 hover:brightness-105 active:scale-[0.98] transition-all flex items-center justify-center gap-3"
                          onClick={shareToWhatsApp}
                        >
                          <MessageCircle size={18} /> Send to WhatsApp
                        </button>
                        
                        <button
                          className="w-full py-5 bg-slate-900 text-white rounded-[1.2rem] font-black text-xs uppercase tracking-widest shadow-xl shadow-slate-900/10 hover:bg-black active:scale-[0.98] transition-all flex items-center justify-center gap-3 disabled:opacity-50"
                          onClick={saveToDashboard}
                          disabled={saving}
                        >
                          {saving
                            ? <><RefreshCw size={18} className="animate-spin" /> {t('common.saving')}</>
                            : <><Save size={18} /> {t('det.saveFieldLog')}</>
                          }
                        </button>
                      </div>
                    </div>
                  ) : (
                    <motion.div
                      initial={{ scale: 0.9, opacity: 0 }}
                      animate={{ scale: 1, opacity: 1 }}
                      className="mt-12 bg-emerald-50 border border-emerald-100 p-8 rounded-[2rem] text-center"
                    >
                      <div className="w-16 h-16 bg-white rounded-full flex items-center justify-center text-emerald-500 mx-auto mb-4 shadow-sm">
                        <CheckCircle2 size={32} />
                      </div>
                      <p className="text-lg font-black text-emerald-900 mb-1">{t('det.successfullyIntegrated')}</p>
                      <p className="text-xs text-emerald-600/70 font-bold uppercase tracking-widest">{t('det.redirecting')}</p>
                    </motion.div>
                  )}
                </motion.div>

              ) : error ? (
                <motion.div
                  key="error"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="dp-result-panel"
                >
                  <div className="dp-error">
                    <div className="dp-error-icon">
                      <AlertCircle size={28} />
                    </div>
                    <p className="dp-error-text">{error}</p>
                  </div>
                </motion.div>

              ) : (
                <motion.div
                  key="idle"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="dp-result-panel"
                >
                  <div className="dp-idle">
                    <div className="dp-idle-icon">
                      <Camera size={28} />
                    </div>
                    <p className="dp-idle-text">{t('det.neuralSensorIdle')}</p>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
        </div>
      </div>

      {/* Loading Progress Bar */}
      <AnimatePresence>
        {loading && (
          <motion.div
            className="fixed top-0 left-0 right-0 h-1 bg-krishi-600 z-50"
            initial={{ scaleX: 0 }}
            animate={{ scaleX: 1 }}
            exit={{ scaleX: 0 }}
            transition={{ duration: 2, ease: "linear" }}
            style={{ transformOrigin: "left" }}
          />
        )}
      </AnimatePresence>

      {/* Error Card */}
      <AnimatePresence>
        {error && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 8 }}
            style={{
              background: '#fdecea',
              border: '1px solid rgba(192,57,43,0.2)',
              borderRadius: 16,
              padding: '16px 20px',
              display: 'flex',
              alignItems: 'flex-start',
              gap: 12,
              marginTop: 16,
            }}
          >
            <AlertTriangle size={18} style={{ color: '#c0392b', flexShrink: 0, marginTop: 1 }} />
            <div style={{ flex: 1 }}>
              <p style={{ fontSize: 13, fontWeight: 700, color: '#c0392b', marginBottom: 4 }}>
                {t('det.scanFailed')}
              </p>
              <p style={{ fontSize: 12, color: 'rgba(192,57,43,0.7)', marginBottom: 10 }}>
                {error}
              </p>
              <button
                onClick={() => setError(null)}
                style={{
                  fontSize: 12, fontWeight: 700,
                  color: '#c0392b',
                  background: 'transparent',
                  border: '1px solid rgba(192,57,43,0.3)',
                  borderRadius: 8, padding: '5px 14px',
                  cursor: 'pointer',
                }}
              >
                {t('common.retry')}
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>


      <style>{`
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
      `}</style>
    </div>
  );
};

export default DetectionPage;
